### ISSUE TITLE
[BUG] - Terug knop gaat letterlijk terug in browser history ipv een link

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-functional-header#32]
**Omschrijf het probleem**
Wanneer je op de knop terug klikt dan verwacht je dat je binnen de webapplicatie terug gaat naar de vorige pagina (breadcrumb gewijs). Maar nu gaat die gewoon terug in je browserhistory.

Wanneer je dus een link met daarin de webpagina, die een Terug knop bevat, toegestuurd krijgt en deze opendoet, dan gaat de "Terug" altijd naar zichzelf verwijzen en lijkt het alsof er niets gebeurd.
Wanneer je deze zelfde link als hierboven hebt, maar deze open doet adhv eerst een leeg tabblad te openen en deze link hierin te copy-pasten, dan gaat de "Terug" naar dit lege tabblad. 
...

**Hoe te reproduceren**
Zie omschrijving, met bijvoorbeeld deze link van DSI2 (je hoeft niet ingelogd te zijn):
https://dsi-oefen.omgeving.vlaanderen.be/fiche-detail/02b21010-6c74-438d-8a8a-99480426b57d

**Gewenst gedrag**
De Terug link moet configureerbaar zijn (zie ook https://github.com/milieuinfo/webcomponent-vl-ui-functional-header/issues/29)

**Screenshots**
/

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome

**Extra info**
zie ook https://github.com/milieuinfo/webcomponent-vl-ui-functional-header/issues/29

**Comment by coemans** [comment]
@Rubenth ik wil gerust een uitbreiding voorzien dat de href configureerbaar is, maar dan zijn jullie applicatief zelf verantwoordelijk om een correcte back link te voorzien. Ik ben benieuwd hoe jullie dit zouden willen toepassen. Afhankelijk van de feedback kan er centraal nog een wijziging gebeuren.

**Comment by coemans** [comment]
Offline besproken, in bepaalde gevallen kan het relevant zijn om applicatief het href attribuut te zetten. De uitbreiding zal toegevoegd worden.
